import {wailsCall} from './wails.js'

/** Typed facade over window.go.ui.App — keep in sync with internal/ui/bind.go */
export const api = {
    getAppInfo: () => wailsCall('GetAppInfo'),
    getStatus: (refresh = false) => wailsCall('GetStatus', refresh),
    getOverviewDetail: () => wailsCall('GetOverviewDetail'),
    getTimeZones: () => wailsCall('GetTimeZones'),
    getFirewallRules: () => wailsCall('GetFirewallRules'),
    changeAccountPassword: (user, p1, p2) => wailsCall('ChangeAccountPassword', user, p1, p2),
    setAccountEnabled: (user, enabled) => wailsCall('SetAccountEnabled', user, enabled),
    setAccountAdmin: (user, admin) => wailsCall('SetAccountAdmin', user, admin),
    disableAccountLockout: () => wailsCall('DisableAccountLockout'),
    enableAccountLockout: () => wailsCall('EnableAccountLockout'),
    setAccountLockoutPolicy: (threshold, durationMin, windowMin) =>
        wailsCall('SetAccountLockoutPolicy', threshold, durationMin, windowMin),
    changeRdpPort: (port) => wailsCall('ChangeRdpPort', port),
    toggleRdp: () => wailsCall('ToggleRdp'),
    clearRdpHistory: () => wailsCall('ClearRdpHistory'),
    clearRdpHistoryByKind: (kind) => wailsCall('ClearRdpHistoryByKind', kind),
    getRdpHistory: () => wailsCall('GetRdpHistory'),
    deleteRdpHistoryEntry: (kind, host, username, detail, sid) =>
        wailsCall('DeleteRdpHistoryEntry', kind, host, username, detail, sid),
    allowFirewallPort: (port) => wailsCall('AllowFirewallPort', port),
    removeFirewallPort: (port) => wailsCall('RemoveFirewallPort', port),
    clearFirewallAllowRules: () => wailsCall('ClearFirewallAllowRules'),
    setFirewallEnabled: (enabled) => wailsCall('SetFirewallEnabled', enabled),
    disablePing: () => wailsCall('DisablePing'),
    enablePing: () => wailsCall('EnablePing'),
    applyTimeZone: (id) => wailsCall('ApplyTimeZone', id),
    saveNTPServer: (server) => wailsCall('SaveNTPServer', server),
    syncNTP: () => wailsCall('SyncNTP'),
    testNTPServer: (server) => wailsCall('TestNTPServer', server),
    lockPC: () => wailsCall('LockPC'),
    restartPC: (delay) => wailsCall('RestartPC', delay),
    shutdownPC: (delay) => wailsCall('ShutdownPC', delay),
    abortPower: () => wailsCall('AbortPower'),
    disableUpdate: () => wailsCall('DisableUpdate'),
    enableUpdate: () => wailsCall('EnableUpdate'),
    disableDefender: () => wailsCall('DisableDefender'),
    enableDefender: () => wailsCall('EnableDefender'),
    checkAppUpdate: () => wailsCall('CheckAppUpdate'),
    downloadAppUpdate: () => wailsCall('DownloadAppUpdate'),
    getAppUpdateInfo: () => wailsCall('GetAppUpdateInfo'),
    applyAppUpdate: () => wailsCall('ApplyAppUpdate'),
}
